name: Deploy Website

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - 'mkdocs.yml'
      - '.github/workflows/**'

env:
  CI: true
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xms4g -Xmx4g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError"
  TERM: dumb

jobs:
  deploy-website:
    name: Generate API docs and deploy website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '22'
      - uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install mkdocs-material mkdocs-minify-plugin
          .buildscript/deploy_website.sh
        env:
          DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
