name: Deploy Website

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - 'mkdocs.yml'
      - '.github/workflows/**'

jobs:
  deploy-website:
    name: Generate API docs and deploy website
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '18'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.job }}-
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install mkdocs-material mkdocs-minify-plugin
          .buildscript/deploy_website.sh
        env:
          CI: true
          JAVA_TOOL_OPTIONS: -Xmx4g -XX:+UseParallelGC
          GRADLE_OPTS: -Dkotlin.incremental.useClasspathSnapshot=false -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError"
          DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
